export const products = [
    {
        id: 1,
        img: "https://dl.dropboxusercontent.com/scl/fi/itwlflzffdzvz1t2ut46w/full-shot-valet-standing-by-car.webp?rlkey=nao869cs6x5zerzaasbp8ht57&st=zmhupt6c&dl=0",
        title: "Tesla Model 3",
        category: "automoviles",
        price: 39.999,
    },
    {
        id: 2,
        img: "https://dl.dropboxusercontent.com/scl/fi/lz1ya8hw3z044fg9pzg5j/toyota-camry.webp?rlkey=2poptoqhg92b4fytc0cb9xox8&st=xytscwmi&dl=0",
        title: "Toyota Camry",
        category: "automoviles",
        price: 25.999,
    },
    {
        id: 3,
        img: "https://dl.dropboxusercontent.com/scl/fi/82mggu7z44dei8fv2bb53/side-view-white-modern-car-outdoors.webp?rlkey=rrmrfz2ene7270khxyqe64p1x&st=r4khgilu&dl=0",
        title: "Ford F-150",
        category: "suv",
        price: 33.999,
    },
    {
        id: 4,
        img: "https://dl.dropboxusercontent.com/scl/fi/50ef9f1hc3q6t7pelodyg/full-shot-people-with-backpacks.webp?rlkey=h6o72ta4b9wpl6t8pvxfcqzgo&st=g4ve8bn4&dl=0",
        title: "Honda CR-V",
        category: "suv",
        price: 26.899,
    },
    {
        id: 5,
        img: "https://dl.dropboxusercontent.com/scl/fi/erh2agcb0q001c1k6au7z/mini-coupe-parking-highway-bridge.webp?rlkey=r0w06ddadeza6sisdnl3zr0lb&st=6qnbybfz&dl=0",
        title: "Porsche 911",
        category: "automoviles",
        price: 101.299,
    },
    {
        id: 6,
        img: "https://dl.dropboxusercontent.com/scl/fi/mfeddsnomlbph1bszfjxj/portrait-modern-young-afro-american-man-helmet.webp?rlkey=7axp6usrmtkc569zpqq2h6kyf&st=9kzp5a7r&dl=0",
        title: "Kawasaki Ninja",
        category: "motocicletas",
        price: 16.799,
    },
    {
        id: 7,
        img: "https://dl.dropboxusercontent.com/scl/fi/s9oblhaejvbcrwdx347a9/man-standing-beside-motorcycle-with-helmet.webp?rlkey=wpsi7sdfpal3176clhs23ewbm&st=s3qkfrk6&dl=0",
        title: "BMW R 1250 GS",
        category: "motocicletas",
        price: 17.999,
    },
    {
        id: 8,
        img: "https://dl.dropboxusercontent.com/scl/fi/3qw2qq6r4mj34hb0xji3g/view-cool-powerful-motorcycle.webp?rlkey=rs03qq5gzmt9oar313cn5mpfc&st=mxz2cxr6&dl=0",
        title: "Ducati Panigale V4",
        category: "motocicletas",
        price: 23.199,
    },
];
